name: publish

on: 
  push:
    branch:
      - publish
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: TEMPLATE_TFM_MAJOR.x.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --property:Version=${{ github.ref_name }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet nuget push --skip-duplicate --api-key=${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json ./**/*.nupkg
