name: publish

on: 
  push:
    branch:
      - master
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x.x
    - name: Pack
      run: dotnet pack RhoMicro.Templates.csproj --output nupkgs --version ${{ github.ref_name }}
    - name: Publish
      run: dotnet nuget push --skip-duplicate --api-key=${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json nupkgs/*.nupkg
